export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST'
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE'


export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'

export const DELETE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST'
export const DELETE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE'

export const FIND_CATEGORY_BY_ID_REQUEST = 'FIND_CATEGORY_BY_ID_REQUEST' 
export const FIND_CATEGORY_BY_ID_SUCESS = 'FIND_CATEGORY_BY_ID_SUCESS' 
export const FIND_CATEGORY_BY_ID_FAILURE = 'FIND_CATEGORY_BY_ID_FAILURE' 

export const FIND_CATEGORY_REQUEST = 'FIND_CATEGORY_BY_CATEGORY_REQUEST'
export const FIND_CATEGORY_SUCCESS = 'FIND_CATEGORY_BY_CATEGORY_SUCCESS'
export const FIND_CATEGORY_FAILURE = 'FIND_CATEGORY_BY_CATEGORY_FAILURE'